@tool
class_name GDLLMSettingsHelp
extends EditorInspectorPlugin
## Injects always-visible descriptions for the plugin's settings into the Editor Settings dialog. The engine offers plugins no description channel there — add_property_info carries only name/type/hint/hint_string and the hover help bit reads engine class docs a plugin can't extend — so each described setting gets a dim caption rendered above its row instead.

## User-facing prose per full setting path, written for a reader who doesn't know harness jargon — each explains its concept (context window, buffer, prune, prompt cache), not just its mechanics. Adding an entry here is all it takes to describe another setting.
const DESCRIPTIONS := {
	GDLLMSettings.MARKDOWN_RESPONSES: "Renders the assistant's replies as formatted Markdown — headings, bold, code blocks, tables — through the MarkdownLabel addon, when that addon is installed in the project. Turn this off to show replies exactly as the model wrote them, as plain text in a standard label: useful when MarkdownLabel is installed for your game but you'd rather this plugin not use it. When the addon isn't installed at all, replies get the same plain rendering automatically, whatever this is set to. Either way nothing is lost or hidden — the text is identical, only the formatting changes — and the role headers and clickable project-file links are kept, since those come from this plugin, not from Markdown. Applies to messages rendered from now on; already-rendered messages keep their look until their session is next rebuilt (reloading the session or restarting the editor). The system prompt follows along: its {markdown_rendering} placeholder asks the model for Markdown formatting while Markdown actually renders, and asks it to write plainly when not — models produce Markdown unprompted, and in the plain label that syntax would show as raw symbols.",
	GDLLMSettings.GAME_AGENT: "Keeps a small autoload (GDLLMGameAgent, visible under Project Settings → Globals) registered in the project — the in-game half of the game-driving tools, which lets the assistant read the running game's UI, click its buttons, play real input, and call methods on live nodes, always through the editor's debugger connection. The autoload does nothing at all in a game launched without a debugger (a normal export stays untouched), and everything it does for the assistant is shown in the chat like any other tool call. Turning this off removes the autoload from the project immediately; games already running keep the agent they launched with until restarted.",
	GDLLMSettings.AUTO_COMPACTION: "Automatically shrinks what the model sees when a conversation is about to outgrow its context window (the fixed number of tokens a model can read at once). Before every request the plugin predicts the next prompt's size; when it would no longer fit, old tool-result outputs are dropped from the model's view — the chat log and the stored transcript always keep everything, and every pass is disclosed in the log. When off, nothing is ever compacted automatically — the chat's Compact button still works on demand — and an overlong conversation risks being truncated silently by the provider (Ollama drops the oldest messages without reporting it), so a red warning posts in the chat once a request is predicted past the window.",
	GDLLMSettings.COMPACTION_BUFFER: "Safety headroom, in tokens, kept between the predicted size of the next request and the model's context window: compaction triggers once the prediction gets within this many tokens of the window. Predictions are estimates and the model's reply also needs room, so the buffer absorbs both. Raise it if conversations still overflow before compaction fires; lower it to use more of the window; 0 waits until the window itself is predicted full. The default covers the worst prediction miss measured in live logs plus a typical reply.",
	GDLLMSettings.COMPACTION_PRUNE_THRESHOLD: "Tool-result pruning never runs while the conversation is predicted smaller than this many tokens, so a small conversation is never touched even when the compaction trigger fires. A skipped pass says so in its log entry. 0 lets pruning run at any size. Pressing the chat's Compact button waives this floor — an explicit request needs no protection from itself.",
	GDLLMSettings.COMPACTION_PRUNE_MIN_RECOVERY: "The fewest tokens a pruning pass must reclaim before it commits. Providers cache the unchanged front of a conversation between requests (the prompt cache), and a prune rewrites history from the oldest dropped result forward, so the next request re-processes everything after that point — a tiny recovery would cost more than it saves. A pass that can't reach this figure prunes nothing and reports the shortfall. 0 commits any recovery.",
	GDLLMSettings.COMPACTION_SUMMARIZATION: "When pruning old tool results alone can't shrink the conversation enough, compaction's second pass has the session's model write a structured summary that stands in for the older part of the conversation in the model's view (the newest share set below stays verbatim). Turn this off to never summarize automatically: pruning stays the only automatic pass, a shortfall it can't cover is noted in the log, a conversation still predicted past the window gets the red over-window warning, and the manual Compact dialog's summarize checkbox starts unchecked (checking it there still runs one summarization on demand). The chat log and stored transcript always keep the full history either way.",
	GDLLMSettings.COMPACTION_IN_SUBAGENTS: "Also compacts inside subagents (the fresh-context helpers the chat delegates tasks to), whose own tool transcripts grow the same way the conversation's does. When a subagent's next request is predicted past its model's context window, its old tool-result outputs are replaced by short markers in what the model sees; the activity panel keeps every full output and each prune is disclosed there. Subagents are never summarized — pruning is their only pass. Ignored while the master switch above is off.",
	GDLLMSettings.COMPACTION_TAIL_PERCENT: "When compaction has to summarize the conversation (pruning old tool results alone wasn't enough), this is the share of the model-visible conversation — newest first — kept verbatim; everything older is replaced in the model's view by a structured summary written by the session's own model. The split never separates a tool call from its result: it lands on a message you wrote. 30 keeps the newest 30% and summarizes the older 70%. The chat log and stored transcript always keep the full history; an orange panel marks where the replacement begins.",
	GDLLMSettings.CACHE_TTL_FALLBACK: "How many seconds a conversation can sit idle before its provider prompt cache is presumed expired. Providers cache the unchanged front of a conversation between requests, but only for a limited lifetime (the cache TTL) — once it lapses, the next request re-processes everything anyway, which makes that moment a free opportunity to trim context (retiring idle tool schemas today; disclosed in the log). Each model can carry its provider's real TTL in the Effort Configuration dialog (the ⚡ button beside the model picker); this value applies to models without one. The default 300 is Anthropic's 5-minute TTL, the shortest documented among supported providers, so trimming never invalidates a cache that was still alive. 0 presumes the cache always expired — only sensible for a provider that caches nothing. On Anthropic sources the effective value (this fallback, or the model's own figure) is also requested with every send: anything over 300 asks for Anthropic's 1-hour cache tier, which doubles the cache-write cost in exchange for the longer lifetime, so raising this fallback affects Anthropic billing, not just the local presumption.",
	GDLLMSettings.COMPACTION_DEBUG: "Turns on the compaction debugging overrides. While off, every debug value is ignored entirely, so a value left over from an old debugging session can't distort real compaction behavior.",
	GDLLMSettings.COMPACTION_DEBUG_THRESHOLD: "Debug only: stands in for the model's context window, in tokens, so compaction can be exercised on a small conversation instead of a genuinely full one. While active the buffer is treated as 0, so the trigger fires exactly at this figure, and the log labels each trigger as debug-tripped. 0 keeps the override off; ignored unless Enable Debugging Tools is on.",
	GDLLMSettings.NEW_SESSION_EDITS: "Whether a newly created chat session starts with its \"Make changes\" toggle on — the per-session switch that lets the assistant modify project files and run project code. Off by default so write permission stays a per-conversation opt-in; this only seeds NEW sessions, and existing sessions keep whatever state their own toggle holds.",
	GDLLMSettings.ALLOW_OUTSIDE_TOOL_CALLS: "Lets the assistant's tools name files and folders outside this project and its user:// data folder. While off (the default), every tool call — reads, searches, writes, moves, copies, deletions — is fenced to the project folder (res://) and the project's user:// data folder: a path that points anywhere else, whether spelled absolutely or climbing out with \"..\", is refused with a message that names this setting. The fence judges only the path text the assistant typed and never inspects where a path REALLY leads, deliberately: a project the user built on symlinks or other outside references keeps working exactly as it does in the editor, since the assistant should be able to affect the project the way the user would. Turn this on only when you genuinely want the assistant reaching arbitrary locations on this machine, with everything your user account can touch; the per-session \"Make changes\" and \"Delete files\" toggles still gate what it may do wherever it reaches, and project.godot, the .godot editor cache, the .git state, and the plugin's own session records (user://gdllm) stay refused by every mutating tool — writes, edits, deletion, moves, copies — either way, judged on the path as spelled: a symlink of your own that reaches one is taken at face value, like every other path. One boundary to know: the fence judges the paths named in TOOL CALLS — code the project itself executes (run_game, run_script, script reloads, game-method calls, all gated by \"Make changes\") runs like any Godot program, with your user account's full reach, wherever that code reads or writes.",
	GDLLMSettings.NEW_SESSION_DELETE: "Whether a newly created chat session starts with its Delete toggle (\"Delete files\") on — the per-session switch that lets the assistant delete project files. Delete is a nested tier of the Edits toggle: it only appears, and only permits anything, while Edits is on — so turning this setting on alone changes nothing until a session also has Edits on. Off by default so deletion stays a per-conversation opt-in; like its sibling setting, this only seeds NEW sessions, and existing sessions keep their own stored state.",
	GDLLMTunables.STREAM_CONNECT_TIMEOUT: "How many seconds the chat waits on a connection that has stopped making progress — name resolution, the socket connect, any TLS handshake, an upload the server stopped accepting (time counted only while no bytes move), and an error reply whose connection never closes — before the request fails or the error is reported with what arrived. The model's own thinking and generation time is never counted against this. Raise it for a slow or remote endpoint (a VPN, a cold-starting proxy, a far-away server); the default 15 comfortably covers a healthy local or cloud source.",
	GDLLMTunables.MODEL_FETCH_TIMEOUT: "How many seconds a model-list fetch or a context-window probe may run before it gives up and reports nothing. A timed-out list fetch leaves the model pickers as they were; a timed-out window probe leaves the model's context window unknown, so the context meter shows ? and cannot color until a later probe succeeds. A shorter value fails faster on an unreachable source; a longer one tolerates a slower host.",
	GDLLMTunables.ANTHROPIC_MAX_TOKENS_FALLBACK: "Every Anthropic request must declare max_tokens — the most tokens the model is allowed to write in its reply. This is the figure sent for a model whose real output cap the plugin hasn't learned yet; once the model list has been fetched, each model's own reported cap is used instead. Some models reject a figure above their cap with an error, so lower this if a rarely-listed model refuses requests; the default suits current large models.",
	GDLLMTunables.ANTHROPIC_COMPLETION_MAX_TOKENS: "The reply-length allowance (max_tokens — the most tokens the model may write) for the plugin's short one-shot Anthropic requests, currently only session-title generation. Titles are a sentence long, so this never needs to be large; it exists as a knob only so no number in the plugin is hardcoded.",
	GDLLMTunables.CHARS_PER_TOKEN: "The characters-per-token ratio behind every token estimate the plugin makes: the context meter, the compaction trigger, prune savings, and the per-message stats footers all divide character counts by this. 4.0 is the usual rule of thumb for English prose; code-dense or non-Latin conversations often run fewer characters per token, so lower it if the meter consistently underestimates what providers report, and raise it for the opposite. Provider-reported exact counts, where available, are always shown as-is — this only shapes the estimates.",
	GDLLMTunables.CONTEXT_METER_WARNING_PERCENT: "How much of the model's context window the PREDICTED next request must fill before the context meter recolors from its resting color to the warning color. The prediction is your unsent message and attachments estimated live, plus the last request's reported prompt tokens — so typing a huge message recolors the meter before anything is sent. Purely presentational: nothing is compacted or blocked at this line. A value above the danger percent below is treated as equal to it.",
	GDLLMTunables.CONTEXT_METER_DANGER_PERCENT: "How much of the context window the predicted next request must fill before the meter takes the error color over the warning color. Like the warning threshold, this only changes the meter's color, not any behavior.",
	GDLLMTunables.TOOL_SEARCH_MAX_RESULTS: "The most tools one tool_search call returns to the model. Every returned tool is also attached to later requests in the conversation (until the idle-retirement setting below reclaims it), so this cap bounds what a single vague search can add to the prompt; when more tools match, the result says so and asks the model to narrow. Raising it makes broad searches costlier in prompt tokens, not better.",
	GDLLMTunables.SCHEMA_RETIRE_IDLE_TURNS: "How many of your messages an attached tool may sit unused before its schema — the tool's full definition and parameter list, which rides along on every request and costs prompt tokens — is dropped from requests again. Retirement always lands at a moment the provider's prompt cache is being rewritten anyway, so it never costs a cache invalidation of its own; a retired tool is one tool_search away from coming back, and the model is told about the mechanism the first time it happens. Raise this if your sessions reuse tools in long cycles; lower it to keep requests leaner.",
	GDLLMTunables.MAX_ATTACHED_SCENE_NODES: "How many selected scene nodes one send will attach when the node attachment toggle is on. Selecting a whole subtree can cover hundreds of nodes, each becoming context the model reads; past this cap the extra nodes are left off, and every attached body states the overflow so neither you nor the model can mistake the attachment for complete.",
	GDLLMTunables.SUMMARY_MIN_HEAD_TOKENS: "When compaction summarizes, the older part of the conversation being replaced is called the head (the newest share, set by Verbatim Recent Tail Percent above, is kept as-is). This is the smallest head (in estimated tokens) worth spending a summarization request on: below it the pass reports itself skipped, since the model call would cost more than it reclaims. A manual focused compaction ignores this floor — its point is shaping what the model carries, not saving tokens.",
	GDLLMTunables.SUMMARY_OUTPUT_RESERVE_TOKENS: "Window room the summarization pass holds back for the summary the model must still have space to WRITE, on top of the request that carries the conversation to be summarized. If summarization fails on a model whose replies run long, raise this; lowering it lets the pass hand the model slightly bigger chunks at the risk of the reply not fitting. A value at or above the model's whole window leaves no room to summarize at all — the pass then reports itself skipped every time.",
	GDLLMTunables.SUMMARY_FAILURE_BREAKER: "How many summarization failures in a row on one model suspend the automatic pass — a circuit breaker so a model that keeps failing to produce a usable summary doesn't burn tokens indefinitely. The suspension is disclosed in the log; it lifts when the session's model changes, and a manual Compact bypasses it (an explicit request runs regardless), with a successful manual pass re-arming the automatic ones. Raise the limit on a flaky endpoint whose failures are transient.",
	GDLLMTunables.SUMMARY_FIT_ATTEMPTS: "A summarization request that is itself too big for the model's window is resized before sending (the fit guard); this is how many resize attempts it gets before giving up. The first shrink is proportional and normally lands; the extras cover conversations whose messages resist an even cut.",
	GDLLMTunables.SUMMARY_FIT_MARGIN_PERCENT: "What percent of the computed size each fit-guard resize actually aims for (see the attempts setting above), so the resized request lands safely inside the window instead of exactly on its line. Lower it (a bigger safety margin) if summarization requests still overflow after resizing — token estimates are least reliable on unusual content.",
	GDLLMTunables.SUMMARY_TARGET_RESERVE_PERCENT: "When a manual compaction names a token target, the request overhead no pass can reclaim (system prompt, tool schemas) comes off the target first; this is the share of the REMAINDER held back for the summary message itself, with the verbatim tail getting what is left. A bigger reserve means a roomier summary and a shorter tail for the same target.",
	GDLLMTunables.PRUNE_KEEP_RECENT_PAIRS: "How many of the newest tool call/result pairs every pruning pass leaves untouched — the model's working set for the turn in flight, which pruning must never yank out from under it. Raise it if the model seems to lose the thread of very recent tool work after a compaction; each kept pair is context that pruning can no longer reclaim.",
	GDLLMTunables.WITHHELD_ESCALATION_THRESHOLD: "How many duplicate-call firings in one run escalate to stopping the loop for a progress summary — withheld repeats (an identical call's result replaced with a short nudge) and re-served mutation repeats (served in full behind a repeat note) both count, since both are the same ignored-warning evidence. Crossing the threshold resets the counter, so the escalation is per-window rather than once ever. It exists because a real session was once watched ignoring 29 such nudges in one turn — stopping after a few ends a run like that early instead of letting it spiral.",
	GDLLMTunables.BROKEN_REMINDER_COOLDOWN: "While the assistant has left files broken on disk, an automatic reminder (\"you left N file(s) BROKEN on disk and have not fixed them yet\") is appended to unrelated tool results. This is how many further tool calls the reminder stays silent for after each firing — so it stays a nudge rather than a per-call nag. 0 reminds on every eligible call.",
	GDLLMTunables.SESSION_TITLE_MAX_CHARS: "The longest a generated session title may run before it is cut with an ellipsis. Titles are written by the Tasks Model and label the session's tab and dropdown entry, so the cap only shapes labels — never the conversation itself.",
	GDLLMTunables.SESSION_SAVE_DEBOUNCE_SECONDS: "How long the session store waits after a change before writing sessions to disk, folding a burst of changes into one write (an agentic turn produces several per second, and rewriting the whole file for each would stall the editor). Structural changes and closing the dock always write immediately — the only loss window is this many seconds of tail on a hard editor crash. Lower it to shrink that window; raise it if disk writes are noticeably stalling a slow machine.",
	GDLLMTunables.REPLAY_FRAME_BUDGET_MS: "How many milliseconds per editor frame a restored session may spend re-rendering its history, yielding the rest so the editor stays responsive while a long conversation backfills over several frames. Raise it on a fast machine to make big sessions appear sooner; lower it if reopening a long session makes the editor stutter.",
	GDLLMTunables.READ_FILE_SUMMARY_THRESHOLD: "The file size (in characters, measured after long data blobs are elided — see the next setting) past which read_file stops returning a text file whole and instead has a fresh-context helper produce a map of it — an overview plus every declaration's signature — so one big file never floods the conversation. The model can still request the full text or an exact line range afterward. Raise it if your model has a big window and you'd rather read more files whole; 0 disables the long-file map, and the tool's own description quotes the live value. Loadable scene and import files take their own shapes regardless (a .tscn its saved node tree, a .import its import map, full text one full: true away); a .tscn too broken to load falls back to plain text and is thresholded like any text file.",
	GDLLMTunables.PACKED_ARRAY_ELIDE_CHARS: "The payload length past which a packed-array literal in a read file is replaced by a count marker. Serialized blobs — embedded images, mesh data, tilemap bytes — run to kilobytes of base64 on a single line that no model can interpret, so eliding them is nearly free context savings. 0 (or -1) disables elision and returns blobs verbatim.",
	GDLLMTunables.SEARCH_CONTEXT_LINES: "The lines of context shown on each side of a search_files match when whole-function excerpting doesn't apply (a non-GDScript file, or a function too long to show whole). The model can ask for more context explicitly, which is honored without a cap — and a bigger explicit ask also raises the whole-function budget to match. The tool's parameter description quotes the live value.",
	GDLLMTunables.SEARCH_MAX_BLOCKS: "The most excerpt blocks (or overview lines) one search_files result carries. A multi-file search that would exceed this collapses into the per-file overview form (see the overview threshold below) rather than truncating excerpts, so lowering it changes the shape of broad results, not just their length. The model's full: true waives it.",
	GDLLMTunables.SEARCH_MAX_FUNCTION_LINES: "The longest enclosing function a search excerpt shows whole at the default context; a longer one falls back to a window around the match, and an explicit context ask raises the budget. Raising it gives richer excerpts for long functions at more context cost per match.",
	GDLLMTunables.SEARCH_OVERVIEW_FILES: "When a search matches more files than this — or its excerpts would blow the block cap above — the result becomes a per-file overview (file names with match counts and function names) instead of excerpts: a map to narrow from rather than a dump. The model's full: true waives it.",
	GDLLMTunables.SEARCH_OVERVIEW_FUNCS: "How many function names one file's overview line carries before the rest collapse to a count.",
	GDLLMTunables.SUGGESTION_LIST_CAP: "The universal cap on short recovery listings: \"did you mean\" suggestions (near-miss class names, setting names, file names, doc entries), the per-list entries in the editor-selection report, and a handful of similar disclosure lists (a node's settable properties on a failed set, for one). One knob because they are all the same idea: enough candidates to recover from, few enough not to flood the result. Refusals that list referencing files cap on the dependent-mentions setting below instead.",
	GDLLMTunables.DEPENDENT_MENTIONS_CAP: "How many referencing files are named individually before the rest are summarized — in the automatic cross-file check after an edit, and in the refusal a rename/move/delete gets while other files still reference the old path. Truncation in the refusal hides real blockers behind a count, so raise this if your project has hub files with many dependents.",
	GDLLMTunables.LIST_DIRECTORY_MAX_ROWS: "The most rows one list_directory result prints before the remainder collapses to a count (an explicit full ask waives the cap). The default clears every legitimate project directory measured (largest: 163 rows) while containing pathological ones like .godot/imported (~700).",
	GDLLMTunables.DEPENDENCY_LINES_CAP: "The most dependency (or dependent) lines one list_dependencies result prints before collapsing the rest to a count; the model's full: true waives the cap and serves every line.",
	GDLLMTunables.RUN_SCRIPT_OUTPUT_LINES: "The most output lines a run_script result relays. It ships more generous than the console default because a finished or killed subprocess's output has nowhere else to live — what this cap drops, only a re-run can reprint.",
	GDLLMTunables.CONSOLE_OUTPUT_LINES: "The line tail read_output returns when the model doesn't ask for a specific count; an explicit ask is honored without a cap. The same figure bounds the output block of every run capture (run_game, suspend_game, reload_game_scripts), so lowering it shortens those too. The tool's own description quotes whatever this is set to, so the model always knows the actual default.",
	GDLLMTunables.CONSOLE_ERROR_ENTRIES: "The entry count read_errors returns when the model doesn't ask for a specific number; an explicit ask is honored without a cap. The same figure bounds the error block of every run capture, and the tool's description quotes the live value.",
	GDLLMTunables.CONSOLE_LINE_MAX_CHARS: "The longest single console line relayed before its remainder is elided with a character count — one runaway print can't flood the conversation. The full line stays visible in the editor's own Output panel.",
	GDLLMTunables.CONSOLE_ERROR_DETAIL_ROWS: "The most detail rows — the engine-side error, source line, and stack frames — relayed per error entry before the remainder collapses to a count.",
	GDLLMTunables.CLASS_MEMBERS_PER_SECTION: "The most members one describe_class section (Properties, Methods, Signals…) prints before it is truncated with a note steering the model to a filter — base classes like Node and Control have hundreds of methods, and a filtered ask is almost always what the question actually needs.",
	GDLLMTunables.SCENE_TREE_MAX_NODES: "The most tree lines one describe_scene result prints before the rest collapse to a count; the model can zoom into a subtree for more.",
	GDLLMTunables.SCENE_NODE_MAX_PROPERTIES: "The most property lines one node's detail view shows before the remainder collapses to a count; a filter reaches anything past the cap.",
	GDLLMTunables.SCENE_NODE_MAX_CONNECTIONS: "The most signal-connection lines one node's detail view shows before the remainder collapses to a count.",
	GDLLMTunables.RENDERED_VALUE_MAX_CHARS: "The longest a single rendered value runs before it is clipped with an ellipsis, wherever tools print values — a scene node's property, a debugger variable at a breakpoint, an animation key. A packed array or long string must never flood a report; most surfaces offer a way to read a clipped value in full (a property filter, a variable filter), though an animation key's clip note only reports the total length.",
	GDLLMTunables.BROWSE_VALUE_MAX_CHARS: "The longest a browsed value runs before it is clipped in listing views — a project setting's value in a filtered list, a script's constant in a class report. A project setting looked up by exact name prints its value whole; a clipped script constant instead points at read_file for the full value.",
	GDLLMTunables.EDIT_EXCERPT_MAX_CHANGED_LINES: "The most changed lines an edit confirmation echoes back before the middle is replaced by a count. The replacement text already sits in the conversation as the edit call's own arguments, so a long echo pays for the same text twice — the head and tail with real line numbers carry the placement, which is the new information.",
	GDLLMTunables.EDIT_EXCERPT_CONTEXT_LINES: "The lines of unchanged context shown on each side of the changed region in an edit confirmation's excerpt — and around each error line in a post-edit validation report's excerpts, so the two edit surfaces frame code the same way.",
	GDLLMTunables.EDIT_ERROR_EXCERPTS: "The most located errors a post-edit validation report (the headless engine check that runs after every edit) shows with a code excerpt; further errors are listed without one, so a badly broken file doesn't flood the result.",
	GDLLMTunables.CHECK_DEATH_TAIL_CHARS: "When a validation subprocess (the headless engine check that runs after every edit) dies before finishing, how much of its most telling output line — the last line carrying an engine error, or failing that the last non-empty line — is quoted into the report: enough to name the cause without spilling an error cascade into the conversation.",
	GDLLMTunables.DOCS_PROSE_MAX_CHARS: "The cap on one describe_docs result's whole prose, applied once to the assembled report rather than per section (per-section caps could still stack past any budget); a longer report is truncated with a note naming the full: true lever (and the Help panel, for you). Bounds what one docs lookup can cost the conversation.",
	GDLLMTunables.DOCS_SEARCH_MAX_HITS: "The most hits one search_docs result lists. Kept small so a search maps the documentation — one line per hit, read in full via describe_docs — rather than dumping prose.",
	GDLLMTunables.DOCS_SNIPPET_CHARS: "The length of the text snippet shown with each search_docs hit, windowed around the first matched word.",
	GDLLMTunables.DOCS_ENUM_VALUES_CAP: "The most values one enum prints in a docs report before the rest are counted and the filter lever is named — @GlobalScope's Key enum alone has 193 values.",
	GDLLMTunables.PROJECT_FILTER_RESULTS_CAP: "The most settings one describe_project prefix filter lists before the remainder collapses to a count; a narrower filter or an exact name reaches the rest.",
	GDLLMTunables.IMPORT_PARAMS_LISTED_CAP: "The most import settings one asset's import report renders before the rest collapse to a count — a texture importer alone declares about 26.",
	GDLLMTunables.SKILL_FALLBACK_DESCRIPTION_CHARS: "When a skill's frontmatter declares no description, the longest excerpt of its first body line used as the fallback description in the skills list.",
	GDLLMTunables.ANIMATION_KEYS_LISTED_CAP: "The most keys listed per animation track before the rest collapse to a count; a zoomed animation view additionally tells the model it can narrow to a time range for the rest.",
	GDLLMTunables.ANIMATION_ANIMATIONS_LISTED_CAP: "The most animations listed per AnimationPlayer before the rest collapse to a count.",
	GDLLMTunables.ANIMATION_TRACKS_LISTED_CAP: "The most tracks rendered per zoomed animation before the rest collapse to a count.",
	GDLLMTunables.TILEMAP_GRID_CELL_CAP: "The largest cell area (width × height) a tilemap grid render covers; past it the grid is withheld and the rect window named instead, since a grid costs roughly one character per cell.",
	GDLLMTunables.TILEMAP_LAYERS_LISTED_CAP: "The most layer names any tilemap report lists before the rest collapse to a count — the empty-layers line, and the \"which layer did you mean\" listings an ambiguous or missing layer name gets back.",
	GDLLMTunables.TILEMAP_SOURCES_LISTED_CAP: "The most sources listed per TileSet before the rest collapse to a count.",
	GDLLMTunables.TILEMAP_SOURCES_PER_LINE_CAP: "The most per-source entries on one layer's tiles line (and atlas coordinates per tile list) before the rest collapse to a count.",
	GDLLMTunables.TILEMAP_SCENE_TILES_LISTED_CAP: "The most scene paths listed for one scenes-collection source before the rest collapse to a count.",
	GDLLMTunables.DEBUGGER_STACK_FRAMES_CAP: "The most stack frames a breakpoint report lists before the deeper remainder is counted; the selected frame is always included even when it sits past the cap.",
	GDLLMTunables.DEBUGGER_VARIABLES_CAP: "The most variables a breakpoint report prints across the frame's locals, members, and globals before the rest are counted.",
	GDLLMTunables.PERF_PROFILE_FUNCTION_ROWS: "The most function/category rows one profile_game report relays before pointing at the Profiler tab for the rest; an explicit limit from the model is honored in full.",
	GDLLMTunables.PERF_PROFILE_VISUAL_ROWS: "The visual profiler's row cap — higher than the function cap by default because render passes form a tree whose leaves carry the cost.",
	GDLLMTunables.PERF_PROFILE_NETWORK_ROWS: "The most per-node rows a network profile relays from each of the Network Profiler's two tables.",
	GDLLMTunables.VRAM_DEFAULT_ROWS: "How many of the largest video-memory consumers read_video_ram lists when the model doesn't ask for a specific count. The tool's description quotes the live value, and a value above the max below behaves (and is quoted) as the max.",
	GDLLMTunables.VRAM_MAX_ROWS: "The hard cap on a read_video_ram row count the model asks for. Quoted live in the tool's description.",
	GDLLMTunables.UNDO_HISTORY_DEFAULT_WINDOW: "How many recent editor actions each undo history reports when the model doesn't ask for a specific window. The tool's description quotes the live value, and a value above the max below behaves (and is quoted) as the max.",
	GDLLMTunables.UNDO_HISTORY_MAX_WINDOW: "The most actions read_undo_history may report per history — it reports two (the active scene's and the global one), so one call can carry up to twice this many action names. Action names are your own work, so the whole history is never dumped. Quoted live in the tool's description.",
	GDLLMTunables.RUN_GAME_DEFAULT_WAIT: "How long run_game watches a launched game before capturing its output, when the model doesn't ask for a specific window — long enough for boot plus first frames. The tool's description quotes whatever this is set to; a value above the max below behaves (and is quoted) as the max.",
	GDLLMTunables.RUN_GAME_MAX_WAIT: "The longest capture window run_game may be asked for, so one call can't stall the conversation for minutes — the assistant waits on the capture before it can continue.",
	GDLLMTunables.RUN_SCRIPT_DEFAULT_TIMEOUT: "run_script's wall-clock timeout when the model doesn't ask for one; a script still running at the timeout is killed and reported as killed. The tool's description quotes the live value, and a value above the max below behaves (and is quoted) as the max.",
	GDLLMTunables.RUN_SCRIPT_MAX_TIMEOUT: "The longest timeout run_script may be asked for — the model may raise the default up to this when a legitimate script needs longer. Quoted live in the tool's description.",
	GDLLMTunables.PROFILE_GAME_DEFAULT_SECONDS: "How long profile_game samples the running game when the model doesn't ask for a specific window. The tool's description quotes the live value, and a value above the max below behaves (and is quoted) as the max.",
	GDLLMTunables.PROFILE_GAME_MAX_SECONDS: "The longest sampling window profile_game may be asked for. Quoted live in the tool's description.",
	GDLLMTunables.SUSPEND_MAX_FRAMES: "The most frames one suspend_game call may advance, keeping frame stepping a bounded look at the game rather than an unattended run. The tool's description quotes the live value.",
	GDLLMTunables.SUSPEND_STEP_BUDGET_MS: "The whole wall-clock budget (in milliseconds) one suspend_game call may spend confirming stepped frames; a game too slow to confirm reports how many frames it managed instead of stalling the conversation.",
	GDLLMTunables.RELOAD_MAX_FILES: "The most changed scripts one reload_game_scripts call pushes to the running game before the list is refused as too broad to be a targeted fix.",
	GDLLMTunables.ENGINE_CHECK_TIMEOUT_MS: "The wall-clock cap (in milliseconds) on one headless validation subprocess — the engine-truth checks that run after edits. They normally finish in well under a second, but a wedged run would otherwise freeze the editor; raise this on a slow machine whose honest checks are being killed early.",
	GDLLMTunables.GAME_PING_TIMEOUT_MS: "How long (in milliseconds) the presence probe waits for the running game's agent to answer before a game-driving tool refuses. The probe only runs when no agent greeting is on record — typically after an editor reload mid-run — and its answer needs the game to process a frame, so a heavy project can genuinely need longer than the default; raise this if game tools claim no agent is present in a game that has one.",
	GDLLMTunables.DEBUGGER_STACK_SETTLE_MS: "How long (in milliseconds) a breakpoint read waits for the stack and variables to arrive from the game before answering with what it has — measured to land 48-173 ms behind the break on a healthy setup, so the default has generous slack. Raise it if break reports on a slow machine arrive empty.",
	GDLLMTunables.DEBUG_GAME_MAX_STEPS: "The most step presses one debug_game call may make; the result traces where each press landed, and the tool's description quotes the live value. Each press can wait several seconds for the break to land on a slow game, so the ceiling stays modest and the whole call is additionally bounded by the step budget below — the model can always call debug_game again for more steps.",
	GDLLMTunables.DEBUG_GAME_STEP_BUDGET_MS: "One debug_game call's whole wall-clock stepping budget (in milliseconds) — the debug counterpart to suspend_game's step budget. When stepping exceeds it, the call stops and reports the presses that landed and where the game stands, rather than holding the conversation while a slow game grinds through the rest.",
	GDLLMTunables.RUN_GAME_LAUNCH_GRACE_MS: "How long (in milliseconds) after launch the editor may report no playing scene before run_game declares the launch failed. Raise it for a project whose boot is genuinely slow, so slow startup isn't mistaken for an instant crash.",
	GDLLMTunables.SUSPEND_FRAME_SETTLE_MS: "How often (in milliseconds) the editor re-checks that a suspend_game stepped frame has landed. Smaller polls confirm frames sooner at the cost of more checks; the whole call is still bounded by the step budget above.",
	GDLLMTunables.SUSPEND_OUTPUT_SETTLE_MS: "How long (in milliseconds) the console is given to catch up before a capture reads it — after a suspend_game stepped frame (a suspended game answers the debugger slowly, and the point of stepping one frame is to see what it printed) and after a reload_game_scripts push, which runs at the game's own pace the same way. Raise it if either capture on a slow machine comes back missing prints.",
	GDLLMTunables.GAME_REPLY_MARGIN_MS: "How much longer (in milliseconds) than the input sequence itself the editor waits for send_game_input's reply before reporting it unanswered. The sequence's own duration is always granted; this is the slack on top for the game to compose its report.",
	GDLLMTunables.GAME_REPLY_TIMEOUT_MS: "How long (in milliseconds) the editor waits for a game command's reply — snapshots and method calls (read_game_ui, inspect_game_node, call_game_method) and suspend_game's per-frame confirmation pings — before reporting the command unanswered rather than waiting forever. Raise it for a game whose frames run long: the agent inside the game can only answer between frames.",
	GDLLMTunables.BREAK_ADVANCE_TIMEOUT_MS: "How long (in milliseconds) one debug_game step press may take to land the next break before the result reports that the game ran on instead. Raise it on a heavy game whose single line takes longer to reach; a resumed game that never breaks again is reported as running either way.",
	GDLLMTunables.BREAK_CONTINUE_WATCH_MS: "After debug_game resumes a paused game, how long (in milliseconds) the editor watches for an immediate second break (the next breakpoint or error) before reporting the game as simply running. Shorter than the step timeout on purpose — most resumes just run on.",
	GDLLMTunables.BREAK_EDITOR_FRAMES: "How many editor frames the script editor is given to build the text control whose gutter carries a breakpoint marker before set_breakpoint reports it couldn't. Raise it only if arming or clearing breakpoints fails on a machine where the script editor opens slowly.",
	GDLLMTunables.VRAM_REPLY_TIMEOUT_MS: "How long (in milliseconds) a read_video_ram refresh waits for the running game's reply before reporting that the game never answered — rather than passing the tab's previous list off as current.",
	GDLLMTunables.CLICK_RECORD_SETTLE_MS: "After an input sequence's pointer steps, how long (in milliseconds) send_game_input keeps waiting for the game's clicked-control records to trickle in. The game reports them at about one per second, so the last click's record can trail the sequence's reply; the default covers one or two clicks, and longer chains are worded to own the lag rather than claim a miss.",
	GDLLMTunables.PERF_HISTORY_SECONDS: "How much performance-monitor history is kept per debugger session, in seconds (the game streams about one sample per second, so this is also the widest window read_performance can summarize — the tool's description quotes the live value). The same figure sizes the network bandwidth-sample ring, where it counts samples rather than seconds since that ring only fills while a network capture runs. Longer history costs a little editor memory per running session.",
	GDLLMTunables.PERF_DEFAULT_WINDOW_SECONDS: "The window read_performance summarizes when the model doesn't ask for a specific one. The tool's description quotes the live value, and a value above the history depth below behaves (and is quoted) as that depth.",
	GDLLMTunables.CLICK_RECORD_CAP: "The most clicked-control records kept per debugger session. Its floor equals one input sequence's step cap (20), so a sequence's own clicks can never fall off its own report; the default keeps double that in hand.",
	GDLLMTunables.TILEMAP_MAX_SET_CELLS: "The most explicit cells one edit_tilemap set/erase call accepts — a bulk shape belongs to fill or replace, and every call's arguments are permanent conversation history.",
	GDLLMTunables.TILEMAP_MAX_FILL_AREA: "The largest rect area (in cells) one edit_tilemap fill, erase, or terrain rect may cover in a single call.",
	GDLLMTunables.TILEMAP_MAX_TERRAIN_CELLS: "The most terrain cells one edit_tilemap call may paint — each is an engine matching step, so huge batches get slow.",
	GDLLMColors.USER_BACKGROUND: "Background wash behind every message you wrote, and behind the row marking a model change — both are yours. Every color on this page ships set to the value the chat log has always used, all of them chosen against the dark editor theme, so a light theme is exactly the case worth retuning here; the revert arrow beside a row puts the original back. An edit repaints the open chats within a moment, except one mid-reply, which repaints when it next reloads.",
	GDLLMColors.USER_CAPTION: "Text color of the disclosure rows on your own turns — the \"You wrote...\" and \"You attached...\" lines — and of the model-change row's caption.",
	GDLLMColors.AGENT_BACKGROUND: "Background wash behind the assistant's final answer, the green counterpart to the wash behind your messages. Also fills the small panel that holds the \"Response generated!\" notice.",
	GDLLMColors.AGENT_CAPTION: "Text color of the \"Generated response…\" row above each answer, and of the \"Response generated!\" notice that appears when a reply lands while you have scrolled away from the bottom.",
	GDLLMColors.REDIRECT_BACKGROUND: "Background wash behind a reply the plugin forced rather than the model volunteering it — what you get when a runaway tool loop is cut short and the model is asked to summarize where it got to. The red counterpart to the assistant's green.",
	GDLLMColors.ERROR_CAPTION: "The color for everything that failed or was cut short: the \"Error\" header on a failed request, redirect and interruption notices, a subagent or background task that ended in failure, and the context meter once the conversation is close to overflowing the model's window.",
	GDLLMColors.TOOL_CAPTION: "Text color of every tool row — \"Called <tool>\" and \"Result from <tool>\" — and of the subagent panels, whose inner runs are made of the same rows.",
	GDLLMColors.ATTACHMENT_CAPTION: "Text color of the rows carrying something you attached to a message (a script, a selection, a scene node). They are shaped like tool rows because the model reads them the same way, but they are colored apart because you supplied them and the model did not go fetch them.",
	GDLLMColors.SUBAGENT_BACKGROUND: "Background wash grouping a subagent's whole inner run — its reasoning, tool calls, and results — into one nested block, so a helper's work reads as belonging to the turn that spawned it. Faint by design: it sits under rows that carry their own colors.",
	GDLLMColors.TASK_BACKGROUND: "Background wash behind work the plugin runs for itself on the small Tasks model, such as generating a session's title. Neutral gray because the run belongs to neither you nor the assistant.",
	GDLLMColors.COMPACTION_BACKGROUND: "Background wash behind a compaction panel — the disclosure that appears whenever the plugin shrinks what the model can see to keep a long conversation inside its context window, and behind the summary it starts from afterwards.",
	GDLLMColors.STATUS_CAPTION: "The dim default for every caption without a role of its own: reasoning traces, the \"generating response…\" placeholder, the sent-to-model disclosures, and the context meter while it has nothing to warn about.",
	GDLLMColors.WARNING_CAPTION: "The color for approaching trouble rather than trouble itself: compaction headers, and the context meter once the predicted next prompt fills the configured warning share of the model's context window (the error color takes over at the danger share; both thresholds live under Gdllm → Context).",
	GDLLMColors.CODE: "Text color of code — both inline spans and fenced blocks — inside chat messages, so code stands out from the prose around it.",
	GDLLMColors.SYSTEM_CAPTION: "Text color of the \"System\" header on a message that belongs to neither you nor the assistant. Rare in practice; it exists so no message can ever render unlabeled.",
	GDLLMColors.THINKING_TEXT: "Text color of a reasoning trace's body — the model's own thinking, shown in full but dimmed so a long trace never competes with the answer it precedes. Raise its brightness to read traces more comfortably.",
	GDLLMColors.FOOTER_TEXT: "Text color of the small bookkeeping footers inside the log — the token-count and speed line beneath a reply, and the \"sent to …\" line beneath your own message — dimmed so the numbers never compete with the conversation.",
	GDLLMColors.SEARCH_HIGHLIGHT: "Wash drawn behind matches when you search the chat log from the field in its header. Translucent by default so the text stays readable over whatever bubble it lands on — keep some transparency, or matches will be highlighted into illegibility.",
}

const CAPTION_ALPHA := 0.6 ## Same dim white the chat log uses for its status captions.
const CAPTION_TOP_MARGIN := 8 ## Binds a caption to the setting row below it rather than the one above.


func _can_handle(object: Object) -> bool:
	# The settings dialogs inspect EditorSettings/ProjectSettings through this internal proxy and nothing else uses it, so this scopes the captions to those dialogs and keeps them out of scene and resource inspectors.
	return object.get_class() == "SectionedInspectorFilter"


func _parse_property(object: Object, _type: Variant.Type, name: String, _hint_type: PropertyHint, _hint_string: String, _usage_flags: int, _wide: bool) -> bool:
	var key := _full_key(name)
	if key == "":
		return false
	# The proxy strips the selected section from names, so confirm this bare name really forwards to our editor setting and not to a same-named property elsewhere.
	if not is_same(object.get(name), EditorInterface.get_editor_settings().get_setting(key)):
		return false
	add_custom_control(_caption(String(DESCRIPTIONS[key])))
	return false


## The full described setting path whose tail matches `name` as the dialog's proxy exposes it — section-stripped ("buffer_tokens"), partially stripped from a parent section ("compaction/buffer_tokens"), or whole — or "" for a property that isn't ours.
func _full_key(name: String) -> String:
	for key in DESCRIPTIONS:
		var full := String(key)
		if full == name or full.ends_with("/" + name):
			return full
	return ""


## A dim, wrapping caption holding `text`, top-margined so it reads as belonging to the setting row rendered beneath it.
func _caption(text: String) -> Control:
	var margin := MarginContainer.new()
	margin.add_theme_constant_override("margin_top", CAPTION_TOP_MARGIN)
	var label := Label.new()
	label.text = text
	label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	label.self_modulate = Color(1, 1, 1, CAPTION_ALPHA)
	margin.add_child(label)
	return margin
